# Generated by Django 5.1.4 on 2024-12-31 09:15

import django.db.models.deletion
import dynamic_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('char', 'Character'), ('text', 'Text'), ('int', 'Integer'), ('decimal', 'Decimal'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('file', 'File'), ('choice', 'Choice'), ('fk', 'Foreign Key'), ('m2m', 'Many to Many')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('dynamic_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dynamic_app.dynamicfield')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='dynamic_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_app.dynamicmodel'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='related_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fields', to='dynamic_app.dynamicmodel'),
        ),
        migrations.CreateModel(
            name='DynamicModelInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_app.dynamicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dynamic_app.models.file_upload_path, validators=[dynamic_app.models.validate_file_type])),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_app.dynamicfield')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dynamic_app.dynamicmodelinstance')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dynamicfield',
            unique_together={('dynamic_model', 'name')},
        ),
    ]
