# Generated by Django 5.1.4 on 2024-12-18 05:14

import django.db.models.deletion
import dynamic_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dynamic_files/', validators=[dynamic_app.models.validate_file_type])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_app.dynamicfield')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dynamic_app.dynamicmodelinstance')),
            ],
        ),
    ]
